name: publish the extension to marketplaces

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: nix-ide*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Open VSX Registry
        run: yarn ovsx publish *.vsix --pat ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        run: yarn vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
